CREATE TABLE comments (
id VARCHAR(255) PRIMARY KEY,
commentDescription VARCHAR (MAX) NOT NULL,
userID VARCHAR(255) FOREIGN KEY REFERENCES stackOverflowUsers(id) ON DELETE CASCADE
date DATE DEFAULT GETDATE() ON DELETE CASCADE NOT NULL,
answerID VARCHAR(255) FOREIGN KEY REFERENCES answers(id) ON DELETE CASCADE
);


