CREATE TABLE votes(
id VARCHAR (255) PRIMARY KEY,
isUpvoted INT DEFAULT 0 NOT NULL, 
answerID VARCHAR (255) FOREIGN KEY REFERENCES answers(id),
userID VARCHAR(255) FOREIGN KEY REFERENCES stackOverflowUsers(id) ON DELETE CASCADE
);



