CREATE TABLE answers (
id VARCHAR(255) PRIMARY KEY,
answerDescription VARCHAR (MAX)  NOT NULL,
isPrefered INT DEFAULT 0 NOT NULL,
userID VARCHAR (255) FOREIGN KEY REFERENCES stackOverflowUsers(id),
questionID VARCHAR(255) FOREIGN KEY REFERENCES questions(id)
);

