
CREATE TABLE stackOverflowUsers(
id VARCHAR(255) PRIMARY KEY NOT NULL,
firstName VARCHAR(MAX),
lastName VARCHAR(MAX) , 
userName VARCHAR(MAX) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(MAX) NOT NULL,
dateJoined DATE  DEFAULT GETDATE() NOT NULL,
github VARCHAR(MAX) NOT NULL,
isActive INT DEFAULT 0,
avatar VARCHAR(MAX),
role VARCHAR (255) DEFAULT 'user'
);

